name: Build C++ Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ lcov libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo find . -name '*.a' -type f -exec cp {} /usr/lib \;
          cd ~

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          ./build.sh -c
